### ISSUE TITLE
Error starting service

### ISSUE THREAD

**Issue by francoisbouchard** [Iristyle/PerfTap#6]
I am getting an error when starting PerfTap service.
The event logs shows error about attribute 'hostName' - see below.
I am using localhost as I have a local statsd server on this box (ruby statsd)
https://github.com/fetep/ruby-statsdserver

Log Name:      Application
Source:        TaskService
Date:          3/5/2013 5:07:33 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      blabla
Description:
Service cannot be started. System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'hostName'. Note that attribute names are case-sensitive. (C:\Program Files\PerfTap\PerfTap.WindowsServiceHost.exe.Config line 18)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean re...

**Comment by santoshsharma0122** [comment]
hello everyone i cant install this PerfTap on my laptop
can someone help me 
i am trying with powershell
what is this error??

The transacted install has completed.
Start-Service : Service 'PerfTap - Synchronize PerfMon to StatsD compatible Graphite listener (PerfTap)' start failed.
At line:223 char:16
+         Start-Service <<<<  PerfTap
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

**Comment by zeugfr** [comment]
On the exe provided, it does not uses "hostname" key but "server" key in configuration.
The "format" key is not recognized too (defaults to StatSite, can't be modified to StatsD).

**Comment by dave2ym** [comment]
Hello,
Had the same problem. After correcting the problem I get another error.

Faulting application name: PerfTap.WindowsServiceHost.exe, version: 0.1.1.0, time stamp: 0x4f14e926
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54504ade
Exception code: 0xe0434352
Fault offset: 0x00014598
Faulting process id: 0x137d8
Faulting application start time: 0x01d0fd18772f1a49
Faulting application path: C:\Program Files\PerfTap\PerfTap.WindowsServiceHost.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: be19198b-690b-11e5-80e9-b8ca3a64e53b
Faulting package full name: 
Faulting package-relative application ID: 

This is on a Windows 2012 R2 Standard.
Any ideas?

**Comment by samshiles** [comment]
It looks like the documentation for non default settings is a bit wrong. I had the same problem as above, but fixed it by editing the config  C:\Program Files\PerfTap\PerfTap.WindowsServiceHost.exe.config to look like:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="perfTapCounterSampling" type="PerfTap.Configuration.CounterSamplingConfiguration, PerfTap" />
    <section name="perfTapPublishing" type="PerfTap.Configuration.MetricPublishingConfiguration, PerfTap" />
  </configSections>
  <perfTapCounterSampling sampleInterval="00:00:01">
    <definitionFilePaths>
      <definitionFile path="CounterDefinitions\system.counters" />
    </definitionFilePaths>
    
    <counterNames />
  </perfTapCounterSampling>
  <perfTapPublishing port="443" server="http://myserver.com" />
</configuration>
